### PR TITLE
Change of files and solved issue #8

### PR DESCRIPTION
**Pull request by pratishthaa**
issue #8  all the files have been added directly from Android studio, so had to delete some files to avoid overlapping. Please review the changes.

### CODE REVIEW

**Comment by abhishekpatelmc** [comment]
Running flutter on Vs code was a better option i guess 
not everyone runs on Android studio

**Comment by pratishthaa** [comment]
Actually, the codes run everywhere it doesn't get affected by which software you are using...you can open these files on VS Code too..it will run perfectly.

**Comment by pratishthaa** [comment]
Please check inbox on Slack.

**Comment by abhishekpatelmc** [comment]
I have messaged on Slack

**Pull request merged**
